---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: source-cluster
    postgres-operator.crunchydata.com/pgbackrest-backup: manual
    postgres-operator.crunchydata.com/pgbackrest-repo: repo1
status:
  succeeded: 1
...
